### PR TITLE
Multiple gamepads support and some improvments.

### PR DESCRIPTION
**Pull request by hetii**
- Added support for psclassic aka Super Nintendo NES / SNES classic mini controller.
- Added support for handling multiple keyboards and other gamepads at the same time for two players.
- Added support for usb devices that can use xfer transfer instead well known hid devices.
- Added support for second nespad controller by bitbanging driver.
- Added new build scrpits including building by docker sandbox.
- Refactor code to exists on separate src dicretory.

### CODE REVIEW

**Comment by hetii** [comment]
@fhoedemakers  Hi ;)
Let's talk about this PR.

As you can see I started innocent just to be able to use my own gamepads.

After some of the time I realize that maybe it's a good idea to refactor the code a bit as well as use some common interface to play with different controllers. This PR is about my result in this are.

I don't claim it's perfect but it seams it works for me at least.

The tricky part was about handling multiple controllers at the same time and not override theirs values between fired callbacks that are vary depending if they are from platform driver/usb hid or usb xfer transfer.

Currently you can test that and attach two keyboards/two usb gamepads and for eg two nespads at the same time.

All of them should be handled and assigned to two players. My multiplayer test game was Bubble Bobble.

General treat this PR more like some preview and start point for discussion in few topics.

For eg one of the issue that I still have is about missing usb enumeration for my gamepads that use xfer transfer, 
after pico restarts, so I need to re-plug usb dongle from it. 

I also  don't have a wii pads that use i2c, so couldn't check if this still works after my changes.

From other minor stuff I also put the code into separate src directory and use new build script. 

Please take your time and tell me what you think about this PR.

How about Bluepad32 integration? Did you maybe start working on it?

**Comment by fhoedemakers** [comment]
Hi,

Thanks for the update. It’s great to see multiplayer support and support for additional USB controllers and keyboards! I indeed need some time to look into this. I need to test each hardware variant in combination with different controllers.

Here are some initial thoughts and remarks based on your comments and code:

- Contrary to the controller for the PlayStation Classic, the (S)NES Classic controllers do not use USB but instead use a Wii-type connector, so how to connect them? I have a PlayStation Classic USB controller, so I can test that. I also have the (S)NES Classic controllers. But I need some clarification about this.
- In the GitHub action and build.sh script, when no SDK is installed, SDK 1.5.0 is downloaded and used for building. Is there a specific reason for not simply using the latest version of the SDK? In the past, it was necessary to use 1.4 due to out-of-memory issues, which were resolved by removing an unused mapper. I’d prefer to stick to the latest SDK version if possible.
- It’s great to see that you’ve restructured the code. I also had plans to put the code in a separate “src” folder.
- Additionally, it’s excellent to see that there’s now “one script to build them all.” 😃  You’ve put a lot of effort into this. I’m just not sure of the extra advantage of using Docker as an option, but that’s okay.
- I did not work on bluepad32.
- There are some minor spelling errors in the changelog.

I’ll come back to it later.


Great work!

Frank

**Comment by hetii** [comment]
Hi.

I'm glad you like this PR project. I will try to clarify a few points.
You can see my configuration in the image below:


On the right you have my ps classic mini controller, at least that how it is advertised by many aliexpress sellers.

It came with a usb dongle and a dongle with a plug like with a wii pad.

I'm not sure if it works on the i2c bus, or if it is just a usb device with a plug end from the wii pad.

To get deeper into this topic, literally yesterday I made myself this yellow board on the fly, it's an i2c-tiny-usb design with an added converter for 3v3, so I'll see if anything reports to me on this pad's bus.

On the left side I have a controller from an old PolyStation console terminated with a DB9 connector, this controller works with the nespad driver. 

The interesting thing about it is that the xyzc buttons, when pressed, alternately report a press and a reset state (so have like autofire).

As for the connection, the clk/lat lat signal lines are common to both controllers. Only the DATA lines are separate.

The nespad version of the controller reads 8 bits, and from what I've seen there are also pads for the snes that are 16 bits, it would make sense to support those as well.

From my subjective tests, it seems that the bitbanging code of the controller for nespad runs smoother than the solution about PIO. Unfortunately, the PIO driver still only supports one pad.

Regarding building the application, I can improve the code to use the master branch, or take the last stable tag, depending on what you prefer (I don't know how stable the master is).

Building via docker has the advantage that you don't have to make a mess of your file system, and it's easy to test other package variants.

This hanging usb port is for testing purposes, as I was also trying to add support for pico-pio-usb from https://github.com/sekigon-gonnoc/Pico-PIO-USB, so that it would be possible to use any pins for the usb host or support two usb ports without having to insert a usb hub. Unfortunately I don't know if I have enough resources here at pio, I generally need to get back to this topic.

I also plan to design a new board that will be sandwiched with this black version from aliexpress, so the whole thing will be as an hdmi dongle. 

Time will tell what will be accomplished.

P.S.
My English is not native, so I apologize in advance if you find any linguistic errors.

Best regards.

**Comment by fhoedemakers** [comment]
Hi,

Thanks for the clarification. Need some time now to test. Will be probably at the end of the week.

Thanks for your patience. I'd wish I had more time for this.

Frank

**Comment by hetii** [comment]
Don't worry and take your time.

I move forward with my i2c testing.

What I discover is that indeed my pads with wii dongle are i2c types.

But they works a bit odd.

First until I pair them with pads, they are not visible on i2c bus. After pairing process they show up on all address:

obraz

Then it seams they have some kind of two modes of works, first that works for me a while was similar to the code that was originate in repository, the only differences was in i2c bus speed, where I need to use 100kHz and increase timeouts for i2c_read_timeout_us method.

So the code read 6 byte and I was able to play games without issues.

But when I try some another game, pico restart itself without any information on console, enter to main menu and start displaying FPS, then from that point where I pressing buttons I don't see any reaction.

After digging a bit, I discover that now I need to read not a 6 bytes but 8 bytes. 

The values are different, so existing mapping doesn't work anymore.

I decide to prepare additional mapping and I discover some other odd behavior.
When have a code like: 

`uint32_t curr_data = 0;`

`if ((buf[7] == 0xFE)) curr_data |= io::GamePadState::Button::UP;`

and press UP button the curr_data is never set, but when I use 

`curr_data =  (buf[7] == 0xFE ? io::GamePadState::Button::UP : 0) | ...`

then it is. I have no clue how this is possible.

So now I try to investigate why sometimes I need to read 6 bytes and sometimes 8 and general how this all works.

Btw I also test  my pads under linux by using code from this websites:
https://forums.developer.nvidia.com/t/howto-nintendo-wii-nunchuck-i2c-grinch-kernel/37527
and there also seams I need to read 8 bytes to get some values.

B.R.

**Comment by fhoedemakers** [comment]
Hi,

Perhaps I'm completely off-topic, but the controllers with the Wii connector types are already supported in the Adafruit Feather configuration. If you change the GPIO pins for WII_SDA and WII_SCL to the correct values, it might already work.

Frank

**Comment by hetii** [comment]
Hi, small update from my side.

You have right, the code for wii pad is there, and of course I set WII_SDA and WII_SCL to the correct values,
but the way how it was written produce some issues.

According http://wiibrew.org/wiki/Wiimote/Extension_Controllers 
there are two ways that can be used to initialize wii extension (pads) and additionally timings are also important, otherwise at least my psclassic  controllers are not initialized properly, and that cause this odd issues where sometimes I needed to read 6 or 8 bytes to get some values.

Moreover the bitwise logic like `((!(buf[5] & 0x01)) ...` sometimes lead to the situation where all bits was set, so pico interpret that like all buttons was press.

This cause race condition in main.cpp where `(pushed & START)` return true and that was the reason why pico back to main menu with fps/firemask enabled as well.

Next issue was in missing re-initialization  code, so when I re-plug my dongle or when it lost connection with controller and I connect it again, it was not configured anymore.

General I pushed next portion of the changes.

What still left is about adding support for second controller by using maybe just one additional GPIO and some discrete components to be able select active pad for reading.

I also don't like this bitwise logic, as it lead to invalid states and for eg when I press UP, pico sees that like UP+LEFT eg:
  
obraz

Beside this, it seams all works stable now at least for me.

B. R.

**Comment by fhoedemakers** [comment]
The help info shown is not correct. 

> ./build.sh 0 RELEASE - build for all supported boards without debug enabled.
./build.sh 1 DEBUG   - build for PimoroniDV board with debug enabled.
./build.sh 2 DEBUG   - build for AdaFruitDVISD board with debug enabled.
./build.sh 3 DEBUG   - build for FeatherDVI board with debug enabled.

Must be:

> ./build.sh build 0 RELEASE - build for all supported boards without debug enabled.
./build.sh build 1 DEBUG   - build for PimoroniDV board with debug enabled.
./build.sh build 2 DEBUG   - build for AdaFruitDVISD board with debug enabled.
./build.sh build 3 DEBUG   - build for FeatherDVI board with debug enabled.

Will try to test the builds later this day.

**Comment by hetii** [comment]
Yes, you have right. I  will fix help message.

USB can act as usb device or host mode.

For board like mine where I have USB-C socket it's enough to connect D+ and D- to usb hub. 

For other boards that use usb micro, I'm not sure if you need dedicated OTG Y cable that have additional pin connected to ground for otg/host mode identification.
Probably not and will work like for in USB-C, so just D+ and D- are required.

For usb controllers order when you connect them to board decide with one is mapped to pad 0 and with one to pad 1.
This is done by logic: `auto &gp = io::getCurrentGamePadState((dev_addr-1) & 1);`
So each device that is enumerated to odd number are assigned to pad0, and each with even number to pad1.

Nes/wii controllers can exist at the same time with multiple usb over usb hub, all should work on the same time.

For Wii code I still do some changes to add support for second pad and fix some corner case when pad is (re)initialized.

**Comment by hetii** [comment]
Second Wii pad seams to work, but to handle it I see  such options.

1. Use two hardware I2C buses, where each go to dedicated pad.
2. Use one software and one hardware I2C bus.
3. Use one or two software implementation of i2c buses and then do multiplexing in the software.
4. Use one hardware I2C bus and I2C hardware multiplexing like from below picture (this is the case that I test now). 
obraz

**Comment by fhoedemakers** [comment]
Hi,

Not sure. Not an expert in this.

Extra hardware options makes it more complex i think.

Frank

**Comment by fhoedemakers** [comment]
Hi,

I tested the pull request with each different hardware combination. To ensure i had a correct working baseline, i first tested each combination with the current binary releases.

Then I rebuilded the pull request and uploaded the binaries to the different hardware combinations.

Below my findings:

### Pimoroni  Pico DV (piconesPlusPimoroniDV)
- Dual Shock 4 and Dual Shock 5 only work after unplugging and plugging in. 
- Controller sometimes stop working. Need to unplug and plug
- When choosing a game, the Pico reboots, flashes the selected rom, but then starts the menu with framrate counter shown. I think it detects an erroneous select + start/A keypress.

### Breadboard and PCB (piconesPlusAdaFruitDVISD)
- Dual Shock 4 and Dual Shock 5 only work after unplugging and plugging in. 
- Can start game, but after reboot need to unplug the controller and plug it back in
- Controller sometimes stop working. Need to unplug and plug
- NES pad (original NES controller) works

### Adafruit Feather (piconesPlusFeatherDVI)
- Dual Shock 4 and Dual Shock 5 only work after unplugging and plugging in. 
- Controller sometimes stop working. Need to unplug and plug
- (NES pad, DS4, DS5, and WII style controllers with nunchuck connector) When choosing a game, the Pico reboots, flashes the selected rom, but then starts the menu with framrate counter shown. I think it detects an erroneous select + start/A keypress.

What is strange to me is that the Breadboard/PCB config can boot into a game.

For now it is all too unreliable for pushing into a new release.  I don't recognise the board you are using on the picture, so it can be a hardware or compatibility issue on the Pico and Adafruit Feather when it is working on your type of board.

Those issues must be fixed first. Then i can move on with the multiplayer tests.

Frank

**Pull request closed without merging**
